### ISSUE TITLE
Trace of original matrix

### ISSUE THREAD

**Issue by hannesbecher** [HighlanderLab/RandPedigreePCA#3]
To be able to compute the variance proportion accounted for by each PC, we need the trace of the original matrix.

Hanbin agreed to add a function for computing the trace to the package. @hanbin973 , feel free to add this to `pca.R`. I am happy to incorporate it into the package/documentation.

**Comment by hanbin973** [comment]
https://github.com/HighlanderLab/RandPedigreePCA/commit/c870380f8239c98de969fd62e8911d7c331f3d88 
I added the function.

**Comment by hannesbecher** [comment]
Great, thank you @hanbin973 !

**Comment by hannesbecher** [comment]
This is great. I can see that the uncertainty around the trace estimate seems to decrease with increasing numbers of random vectors.
![image](https://github.com/user-attachments/assets/824d383f-0f62-4f6c-abca-1214984c6d6b)

Skorski, M. (2021) give an expression (equation 10) that looks that the relative error depends on the number of random vectors only, not the size of the original matrix. I wonder what is a good error level to aim for?  E.g. following their equation 10, one would require almost 40k random vectors for an error margin of 2% at a probability of 95%. This can become computationally quite costly compared to the random PCA itself.

# Skorski, M. (2021). Modern Analysis of Hutchinson’s Trace Estimator.
#' 2021 55th Annual Conference on Information Sciences and Systems (CISS), 1–5.
#' https://doi.org/10.1109/CISS50987.2021.9400306

**Comment by hanbin973** [comment]
I just realized that this is an overkill. Isn't the diagonal of the GRM constant? I mean just 1. Then the trace should be the sample size. We don't have to compute anything.

**Comment by hannesbecher** [comment]
That would be great! I find it puzzling though that the Hutchinson trace estimate is around 3450 for the simulated example while the sample size is 2600. Can you make sense of that, @hanbin973 ?

```
> linv <- importLinv("../datasets/pedLInv.mtx")
> dim(linv)
[1] 2600 2600 # sample size is 2600
> randTraceHutchinson(linv, numVectors = 40000)
[1] 3451.279 # trace relative accuracy 2% at a probability of 95%
```

**Comment by hannesbecher** [comment]
Taking the diagonal of the relationship A matrix, the values are mostly non-one. This is true for both the A matrix exported from the small simulation and the matrix reconstituted from L inverse (L^I^T * L^I)^I. The diagonal values sum to 3446.95. (If I sum the diagonal of A^I, I get 12465.42.) Anyway, all matrices have dimensions 2600x2600.

**Comment by hannesbecher** [comment]
I should say I think your function is correct, @hanbin973 . The simulated example is small enough to compute the trace 'naively'. This gives comparable results to your function.

**Comment by hannesbecher** [comment]
@hanbin973 when computing the variance proportions, we need the sum of the variances as the denominator. *But the trace is the sum of the standard deviations.* Squaring that sum is not the same as summing over the squared std. dev. values. So, I am not sure if we can actually get to the summed variance values from the trace estimate.

**Comment by hanbin973** [comment]
We can do the matvec twice to get the square of eigenvalues, if that's needed

Besides, R prcomp stdev is the eigenvalues divided by sample size. If we prcomp A, the resulting eigenvalues are indees the variance and not stdev in the usual sense.

**Comment by hannesbecher** [comment]
Good! Maybe I got confused. The reason is the way that variance proportions are reported by R's summary.prcomp:

https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/library/stats/R/prcomp.R#L97

They square their "standard deviation" values to get variances and then divide these squares by their sum. Does that make sense at all?

**Comment by hannesbecher** [comment]
As mentioned by @gregorgorjanc on Slack, we can get the individuals' inbreeding coefficients from the pedigree. These correspond to the relationship matrix's diagonal values - 1. So, when using the pedigree as a starting point for the `rppca` function, the correct variance proportions are returned. Or at least, they match what `prcomp` returns when run on the **L** (not inverse) matrix.

**Comment by hannesbecher** [comment]
The question is now: "Do we still want to allow users to start from the **L**^I matrix?" That way, if we want to know the variance proportions, we need to estimate the diagonal of the associated **A** matrix, which is costly with the Hutchinson method (although @hanbin973 said there is a more efficient way to estimate that).

Is it conceivable that a user doesn't have access to the pedigree but only to **L**^I, @gregorgorjanc ?

**Comment by hannesbecher** [comment]
OK. Done.
We now have rppca.pedigree that does everything starting from a pedigreeTools pedigree object. We also have rppca.spam that expects Linvers in spam format. This computes variance components only if totVar is specified. I'll keep the randTraceHutchinson function. If we decide to implement something more efficient in the future, we can always do that.

**Comment by gregorgorjanc** [comment]
@hannesbecher you can keep the `randTraceHutchinson()` as unexported.
