### ISSUE TITLE
Variance components don't seem to match between rppca and prcomp

### ISSUE THREAD

**Issue by hannesbecher** [HighlanderLab/RandPedigreePCA#5]
Hi @hanbin973 

I think in our chat on Friday, you mentioned that the eigenvalues returned by rsvd should be equivalent to those of naive PCA (for the respective PCs). But I cannot make these match. There is some comparison code at the bottom of `hello.R`. Here is the output. I would have expected that the Standard deviation row would match `d` or `sqrt(d)`. Is it possible that this has to do with centering/scaling?

```
# no great resemblance between these values of
#  SD from prcomp and d from random svd
summary(pcaaNocenter)$importance[,1:10]
#                              PC1      PC2      PC3      PC4       PC5       PC6     PC7       PC8
#  Standard deviation     17.43141 14.79962 1.417906 1.330322 0.6352784 0.5078248 0.44014 0.3378062
#  Proportion of Variance  0.57397  0.41374 0.003800 0.003340 0.0007600 0.0004900 0.00037 0.0002200
#  Cumulative Proportion   0.57397  0.98770 0.991500 0.994840 0.9956100 0.9960900 0.99646 0.9966800
#                               PC9      PC10
#  Standard deviation     0.2848558 0.2750638
#  Proportion of Variance 0.0001500 0.0001400
#  Cumulative Proportion  0.9968300 0.9969700
pc$d
#  [1] 888.65996 754.49060  72.27821  67.81399  32.01035  25.14347  21.42995  14.56372  12.50480
#  [10]  12.15989
sqrt(pc$d)
#  [1] 29.810400 27.467992  8.501659  8.234925  5.657769  5.014326  4.629250  3.816244  3.536213
#  [10]  3.487103
```

**Comment by hanbin973** [comment]
The latter is the square root of the former. This is because RandSVD is acting on a matrix `B` such that `B^2=A` where `A` is the genetic relatedness matrix.

**Comment by hannesbecher** [comment]
I know, and I computed the square root. The pc object is the result of rsvd/rppca. But these two vectors seem not to be related to the row "Standard deviation" above, which is the output of R's built-in prcomp.

**Comment by hannesbecher** [comment]
Thank for digging this out, @hanbin973 
Division by sqrt(sample size -1) makes the numbers match.
Resolved.
